% define path to the community models with diet constraints, generated by mgPipe
modPath = pwd filesep 'Diet'];

% run individual secretion fluxes
[minFluxes,maxFluxes,fluxSpans] = predictMicrobeContributions(modPath);